// AUTO-GENERATED by /api/push-app and /api/mcp. Edit src/apps/<slug>/index.tsx, not this file.
import type { RegisteredApp } from '@/types/app';

export const APP_REGISTRY: RegisteredApp[] = [
  {
    meta: {
      id: "grocery-list",
      name: "Grocery List",
      description: "Add items, check off, clear. Synced.",
      icon: "🛒",
      route: "grocery-list",
      needsPersistence: true,
      status: "active",
    },
    load: () => import("./grocery-list"),
  },
  {
    meta: {
      id: "pomodoro",
      name: "Pomodoro",
      description: "25/5 focus timer. Counts today’s sessions.",
      icon: "🍅",
      route: "pomodoro",
      needsPersistence: true,
      status: "active",
    },
    load: () => import("./pomodoro"),
  },
];

export function findApp(id: string): RegisteredApp | undefined {
  return APP_REGISTRY.find((a) => a.meta.id === id);
}
