// AUTO-GENERATED by /api/push-app and /api/mcp. Edit src/apps/<slug>/index.tsx, not this file.
import type { RegisteredApp } from '@/types/app';

export const APP_REGISTRY: RegisteredApp[] = [
  {
    meta: {
      id: "counter",
      name: "Counter",
      description: "Simple +1 counter.",
      icon: "🔢",
      route: "counter",
      needsPersistence: true,
      status: "active",
    },
    load: () => import("./counter"),
  },
  {
    meta: {
      id: "grocery-list",
      name: "Grocery List",
      description: "Add items, check off, clear. Synced.",
      icon: "🛒",
      route: "grocery-list",
      needsPersistence: true,
      status: "active",
    },
    load: () => import("./grocery-list"),
  },
  {
    meta: {
      id: "ping",
      name: "Ping",
      description: "Tap to increment.",
      icon: "📡",
      route: "ping",
      needsPersistence: true,
      status: "active",
    },
    load: () => import("./ping"),
  },
  {
    meta: {
      id: "pomodoro",
      name: "Pomodoro",
      description: "25/5 focus timer. Counts today’s sessions.",
      icon: "🍅",
      route: "pomodoro",
      needsPersistence: true,
      status: "active",
    },
    load: () => import("./pomodoro"),
  },
  {
    meta: {
      id: "workout-streak",
      name: "Workout Streak",
      description: "Tap to mark today done. Tracks current and longest streak.",
      icon: "🔥",
      route: "workout-streak",
      needsPersistence: true,
      status: "active",
    },
    load: () => import("./workout-streak"),
  },
];

export function findApp(id: string): RegisteredApp | undefined {
  return APP_REGISTRY.find((a) => a.meta.id === id);
}
