// AUTO-GENERATED by /api/push-app and /api/mcp. Edit src/apps/<slug>/index.tsx, not this file.
import type { RegisteredApp } from '@/types/app';

export const APP_REGISTRY: RegisteredApp[] = [
  {
    meta: {
      id: "counter",
      name: "Counter",
      description: "Simple +1 counter.",
      icon: "🔢",
      route: "counter",
      needsPersistence: true,
      status: "active",
    },
    load: () => import("./counter"),
  },
  {
    meta: {
      id: "grocery-list",
      name: "Grocery List",
      description: "Items to acquire. Check off as gathered.",
      icon: "",
      route: "grocery-list",
      needsPersistence: true,
      status: "active",
    },
    load: () => import("./grocery-list"),
  },
  {
    meta: {
      id: "ping",
      name: "Ping",
      description: "Tap to increment.",
      icon: "📡",
      route: "ping",
      needsPersistence: true,
      status: "active",
    },
    load: () => import("./ping"),
  },
  {
    meta: {
      id: "pomodoro",
      name: "Pomodoro",
      description: "Focused work in measured intervals.",
      icon: "",
      route: "pomodoro",
      needsPersistence: true,
      status: "active",
    },
    load: () => import("./pomodoro"),
  },
  {
    meta: {
      id: "water-tracker",
      name: "Water",
      description: "A record of water taken today.",
      icon: "",
      route: "water-tracker",
      needsPersistence: true,
      status: "active",
    },
    load: () => import("./water-tracker"),
  },
  {
    meta: {
      id: "workout-streak",
      name: "Training Log",
      description: "A record of days trained.",
      icon: "",
      route: "workout-streak",
      needsPersistence: true,
      status: "active",
    },
    load: () => import("./workout-streak"),
  },
];

export function findApp(id: string): RegisteredApp | undefined {
  return APP_REGISTRY.find((a) => a.meta.id === id);
}
