/**
 * POST /api/push-app
 *
 * Auth: Authorization: Bearer ${FOUNDRY_PUSH_SECRET}
 *
 * Body (JSON):
 *   {
 *     "id": "meal-plan",                  // lowercase, hyphenated, [a-z][a-z0-9-]{1,39}
 *     "name": "Meal Plan",
 *     "description": "Weekly dinners for Andre & Isabel",
 *     "icon": "🍽️",
 *     "route": "meal-plan",                // typically same as id
 *     "componentCode": "<full TSX module>",// MUST default-export a React FC
 *     "needsPersistence": false
 *   }
 *
 * What happens:
 *   1. Validates bearer + payload.
 *   2. If GITHUB_TOKEN is set, commits the component to
 *      `src/apps/<id>/index.tsx` AND updates `src/apps/registry.ts`
 *      to import + register the app.
 *      Vercel's GitHub integration then auto-deploys.
 *   3. Upserts the app metadata in Supabase `foundry_apps` so the
 *      dashboard can toggle status at runtime.
 *
 * If GitHub env isn't configured, only step 3 runs and a clear message is
 * returned — the deploy step becomes Andre's responsibility.
 */
import { commitFileToGitHub, env, isValidId, json, requireAuth, sb } from './_lib';

export const config = { runtime: 'edge' };

interface PushAppBody {
  id?: string;
  name?: string;
  description?: string;
  icon?: string;
  route?: string;
  componentCode?: string;
  needsPersistence?: boolean;
}

export default async function handler(req: Request): Promise<Response> {
  if (req.method !== 'POST') {
    return json({ error: 'Method not allowed' }, { status: 405 });
  }
  const e = env();
  const authError = requireAuth(req, e);
  if (authError) return authError;

  let body: PushAppBody;
  try {
    body = (await req.json()) as PushAppBody;
  } catch {
    return json({ error: 'Invalid JSON body' }, { status: 400 });
  }

  const { id, name, description = '', icon, componentCode, needsPersistence = false } = body;
  const route = body.route ?? id;

  if (!id || !isValidId(id)) {
    return json({ error: 'Invalid `id` (lowercase, hyphenated, 2-40 chars)' }, { status: 400 });
  }
  if (!name || !icon || !componentCode || !route) {
    return json(
      { error: 'Missing required fields: name, icon, route, componentCode' },
      { status: 400 },
    );
  }
  if (!/export\s+default/.test(componentCode)) {
    return json(
      { error: 'componentCode must contain `export default` for the component' },
      { status: 400 },
    );
  }

  const client = sb(e);
  const upsert = client
    ? await client.from('foundry_apps').upsert(
        {
          id,
          name,
          description,
          icon,
          route,
          needs_persistence: needsPersistence,
          status: 'active',
        },
        { onConflict: 'id' },
      )
    : { error: { message: 'Supabase not configured' } };

  // Commit to GitHub (optional but recommended).
  let commit: { sha?: string; skipped?: string } = {};
  if (e.GITHUB_TOKEN) {
    const filePath = `src/apps/${id}/index.tsx`;
    const result = await commitFileToGitHub(e, {
      path: filePath,
      content: componentCode,
      message: `Foundry: push app ${id}`,
    });
    if (!result.ok) {
      return json({ error: result.error, supabase: upsert }, { status: result.status });
    }
    commit = { sha: result.sha };

    // Update registry.ts. We fetch, regenerate, and commit.
    const regenResult = await regenerateRegistry(e);
    if (!regenResult.ok) {
      // Non-fatal — metadata is in DB; just warn.
      commit = { ...commit, skipped: regenResult.error };
    }
  } else {
    commit = { skipped: 'GITHUB_TOKEN not set; only metadata persisted to Supabase' };
  }

  return json({
    success: true,
    id,
    route: `/app/${route}`,
    commit,
    supabase: upsert.error ? { error: upsert.error.message } : { ok: true },
  });
}

/**
 * Regenerates `src/apps/registry.ts` from foundry_apps rows. Best-effort: if
 * Supabase isn't available we leave the file alone and the caller is
 * expected to maintain it manually.
 */
async function regenerateRegistry(
  e: ReturnType<typeof env>,
): Promise<{ ok: true } | { ok: false; error: string }> {
  const client = sb(e);
  if (!client) return { ok: false, error: 'Supabase not configured' };
  const { data, error } = await client
    .from('foundry_apps')
    .select('id,name,description,icon,route,needs_persistence,status')
    .order('id');
  if (error || !data) return { ok: false, error: error?.message || 'registry read failed' };

  const lines: string[] = [];
  lines.push('// AUTO-GENERATED by /api/push-app. Edit src/apps/<slug>/index.tsx, not this file.');
  lines.push("import type { RegisteredApp } from '@/types/app';");
  lines.push('');
  lines.push('export const APP_REGISTRY: RegisteredApp[] = [');
  for (const row of data as Array<{
    id: string;
    name: string;
    description: string | null;
    icon: string;
    route: string;
    needs_persistence: boolean | null;
    status: 'active' | 'archived';
  }>) {
    lines.push('  {');
    lines.push('    meta: {');
    lines.push(`      id: ${JSON.stringify(row.id)},`);
    lines.push(`      name: ${JSON.stringify(row.name)},`);
    lines.push(`      description: ${JSON.stringify(row.description ?? '')},`);
    lines.push(`      icon: ${JSON.stringify(row.icon)},`);
    lines.push(`      route: ${JSON.stringify(row.route)},`);
    lines.push(`      needsPersistence: ${row.needs_persistence ? 'true' : 'false'},`);
    lines.push(`      status: ${JSON.stringify(row.status)},`);
    lines.push('    },');
    lines.push(`    load: () => import(${JSON.stringify(`./${row.id}`)}),`);
    lines.push('  },');
  }
  lines.push('];');
  lines.push('');
  lines.push('export function findApp(id: string): RegisteredApp | undefined {');
  lines.push('  return APP_REGISTRY.find((a) => a.meta.id === id);');
  lines.push('}');
  lines.push('');

  const result = await commitFileToGitHub(e, {
    path: 'src/apps/registry.ts',
    content: lines.join('\n'),
    message: 'Foundry: regenerate app registry',
  });
  if (!result.ok) return { ok: false, error: result.error };
  return { ok: true };
}
